### ISSUE TITLE
offset

### ISSUE THREAD

**Issue by wangtianshang** [elasticsearch-dump/elasticsearch-dump#812] opened 2021-07-05 12:32 UTC
Mon, 05 Jul 2021 12:31:25 GMT | starting dump
Mon, 05 Jul 2021 12:31:25 GMT | Warning: offsetting 10 rows.
Mon, 05 Jul 2021 12:31:25 GMT |   * Using an offset doesn't guarantee that the offset rows have already been written, please refer to the HELP text.
Mon, 05 Jul 2021 12:31:25 GMT | Error Emitted => {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"},"status":400}
Mon, 05 Jul 2021 12:31:25 GMT | Error Emitted => {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"},"status":400}
Mon, 05 Jul 2021 12:31:25 GMT | Total Writes: 0
Mon, 05 Jul 2021 12:31:25 GMT | dump ended with error (get phase) => BAD_REQUEST: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"},"status":400}

**Comment by wangtianshang** [comment] 2021-07-05 12:32
elasticdump --limit=10000 --maxRows=20000000 --offset=10 --input=http://x.x.x.x:9200/index --output=/root/test.json

**Comment by wangtianshang** [comment] 2021-07-05 12:39
node : v10.24.0
elastucdumpo : 6.72.0
elasticsearch : 6.8.5

**Comment by ferronrsmith** [comment] 2021-07-05 15:04
duplicate of #796

> **If you are using Elasticsearch version 6.0.0 or higher the offset parameter is no longer allowed in the scrollContext**

**Closed by ferronrsmith** 2021-07-05 15:04 UTC

**Comment by wangtianshang** [comment] 2021-07-06 05:57
> duplicate of #796
> 
> > **If you are using Elasticsearch version 6.0.0 or higher the offset parameter is no longer allowed in the scrollContext**

ok，thanks
