### ISSUE TITLE
RangeError: Invalid string length     at JSON.stringify

### ISSUE THREAD

**Issue by miladsoltaniantemp** [elasticsearch-dump/elasticsearch-dump#1037] opened 2024-04-29 08:03 UTC
my index is about 2 TB, here is my command, and I got this error ! 

docker run --rm -ti -v /root/xxx:/tmp/ elasticdump/elasticsearch-dump --output=/tmp/xxxx_29_4_2024.json --input=http://xxxx:xxx@xxx:9200/xxx-xxx--type=data --limit 4096 --retryAttempts 10000 --timeout 10000  --file-size 5G --scrollTime 24h

Mon, 29 Apr 2024 06:27:51 GMT | got 4096 objects from source elasticsearch (offset: 2895872) 
Mon, 29 Apr 2024 06:27:52 GMT | sent 4096 objects to destination file, wrote 4096 (node:7) 
UnhandledPromiseRejectionWarning: RangeError: Invalid string length     at JSON.stringify (<anonymous>)     at Object.stringify (/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:56:10)     at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/lib/transports/__es__/_helpers.js:88:55)     at Request._callback (/usr/local/lib/node_modules/elasticdump/node_modules/lodash/lodash.js:10118:25)     at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:151:19)     at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:192:10)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:95:5) 
(Use `node --trace-warnings ...` to show where the warning was created) (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
 (rejection id: 1) (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by miladsoltaniantemp** [comment] 2024-04-30 13:07
another one 

Tue, 30 Apr 2024 12:59:35 GMT | sent 10000 objects to destination file, wrote 10000
buffer.js:821
    return this.utf8Slice(start, end);
                ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (buffer.js:821:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1130:39)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:475:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1070:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_STRING_TOO_LONG'
}

**Comment by ferronrsmith** [comment] 2024-05-02 00:04
duplicate of https://github.com/elasticsearch-dump/elasticsearch-dump/issues/821

**Closed by ferronrsmith** 2024-05-02 00:04 UTC
