### ISSUE TITLE
there is a way to bypass "REQUEST_ENTITY_TOO_LARGE"?

### ISSUE THREAD

**Issue by kobishalom** [elasticsearch-dump/elasticsearch-dump#955] opened 2023-02-11 00:56 UTC
Hey,

I'm trying to copy between AWS-Opensearch and I got the following error:
`Error Emitted => {"Message":"Request size exceeded 104857600 bytes"}`
`dump ended with error (get phase) => REQUEST_ENTITY_TOO_LARGE: {"Message":"Request size exceeded 104857600 bytes"}`

I know that in AWS there is a limit of 100MB per batch transfer (if I understand correctly), there is a parameter maybe that can set each transfer/batch to that limit and by that will not need to worry about that kind of error?

**Comment by ferronrsmith** [comment] 2023-02-11 01:27
Duplicate of https://github.com/elasticsearch-dump/elasticsearch-dump/issues/855

You need to use the '--limit' property to limit the amount of documents sent to ES, you're sending too much.

**Comment by kobishalom** [comment] 2023-02-11 07:12
@ferronrsmith - the limit is 100MB, sometimes using a limit of 100 is working, and sometimes even 10 is not working, this is why I'm asking if it is possible to take each operation 100MB, by that we will know for sure it will works

**Comment by ferronrsmith** [comment] 2023-02-11 07:58
Is the input from a file ? It might be possible to limit based on the input size being passed to the output, but even that is a little tricky.


It's a not exactly a simple problem

**Comment by kobishalom** [comment] 2023-02-11 08:14
@ferronrsmith - it's between AWS Opensearch, I think an idea.
but should test it or understand that little bit more, 
1) run with the parameters "--skip-existing=true", "--ignore-errors=true" and "--delete".
by that, the first operation will copy the most and will remain only the "problematic" docs.
2) tun it again but with "--limit" and now it will run on small number of docs so it will be faster

**Comment by ferronrsmith** [comment] 2023-02-11 17:30
Seems like a hack, more than a solution to the problem. **REQUEST_ENTITY_TOO_LARGE** is a server issue, and any attempt to "fix" to me seems like an hack.

I was thinking about ti last night. I think we can split the data being the data being sent to the server.


if REQUEST_ENTITY_TOO_LARGE
split datset / 2
send parts async (etc)

**Closed** 2023-02-12 02:26 UTC

**Comment by kobishalom** [comment] 2023-02-12 06:47
yeah, because of the limit that we can't change, I think the AWS OpenSearch only should work by the limit of 100 or 10.
do you think it is possible?

**Comment by kobishalom** [comment] 2023-02-12 07:54
yeah, because of the limit that we can't change, I think the AWS OpenSearch only should work by the limit of 100 or 10.
do you think it is possible?
