### ISSUE TITLE
[ElasticDump does not have a way to sign a execution from an AWS ECS task ]

### ISSUE THREAD

**Issue by niladriforu** [elasticsearch-dump/elasticsearch-dump#713] opened 2020-06-25 07:35 UTC
**Is your feature request related to a problem? Please describe.**
Like requests module in python , elasticdump does not have a way to pass the authentication parameter. 
This is restricting its usage. In my work scenario, we have a solution in AWS cloud. We are using  the esdump through an  ECS task. The task role already has permissions to access the elasticsearch service. But the Elasticsearch has role based IAM policies. In order to ensure elasticdump can talk to the elasticsearch service , we need to pass the authentication in the call. 
**Describe the solution you'd like**
Elasticdump giving us a permission to pass the aws role based authentication. 
**Describe alternatives you've considered**
We went live with the project when our elasticsearch service was a public endpoint. Thats why ESDump was working perfectly. Ever since we have put this exception , esdump has ceased to work. So, currently, we are looking at going away from esdump utility and have an alternate design.

**Give some examples of implementations**
Already gave above.

**Additional context**
Our AWS Elasticsearch service is still a public endpoint , with AWS IAM role permissions. We tried IP based IAM policies as well but our AWS ECS task is on a fargate cluster. That means the subnet ips are private ips. Looks like AWS allows private ips to be put in IAM policy of a ES service if the ES service is on private network as well ( VPC ) . We were not able to use this solution as well.

**Comment by ferronrsmith** [comment] 2020-06-25 14:41
Understood, it should be possible to implement this via the aws-sdk that’s used underneath, but I don’t use AWS or have access to any instance. 

If your submit a PR I’ll gladly merge it or you can fork ESDump and implement these changes to fit your needs.

**Comment by ferronrsmith** [comment] 2020-06-26 00:42
duplicate of  #711

**Comment by niladriforu** [comment] 2020-06-26 08:20
> Understood, it should be possible to implement this via the aws-sdk that’s used underneath, but I don’t use AWS or have access to any instance.
> 
> If your submit a PR I’ll gladly merge it or you can fork ESDump and implement these changes to fit your needs.

Thanks for the reply. From your documentation, I see this piece : 

--awsAccessKeyId
--awsSecretAccessKey
                    When using Amazon Elasticsearch Service protected by
                    AWS Identity and Access Management (IAM), provide
                    your Access Key ID and Secret Access Key.
                    --sessionToken can also be optionally provided if using temporary credentials


This is exactly what I was looking for. Does this mean this has already been taken care of? If yes, can I pass on frozen credentials in awsAccessKeyId and awsSecretAccessKey?

**Comment by ferronrsmith** [comment] 2020-06-26 11:40
👍🏾

**Closed** 2020-06-26 11:41 UTC

**Comment by niladriforu** [comment] 2020-07-09 07:48
Just to let you guys know, those options worked with frozen credentials from boto3. Thanks! Session token is not optional in that case, we need to pass explicitly ( we get it from frozen credentials too ) . May be it is a good idea to put it in readme as it is mentioned as optional.
