### ISSUE TITLE
Issue while dumping template to file - linked to https://github.com/elasticsearch-dump/elasticsearch-dump/issues/742

### ISSUE THREAD

**Issue by gs-catapult** [elasticsearch-dump/elasticsearch-dump#743] opened 2020-11-17 03:51 UTC
Linked issue: https://github.com/elasticsearch-dump/elasticsearch-dump/issues/742

Original issue (https://github.com/elasticsearch-dump/elasticsearch-dump/issues/742) is already in closed status, Hence this new issue is raised.

Could you please investigate bit more on this below points.

1. If there are errors, why elasticsearch-dump report blank errors **'Error: {}'**

2. elasticsearch-dump should report the actual error from elasticsearch, if any.
3. Also It appears there were no errors raised by elasticsearch. When template is fetched with curl, it respond with empty json. 
This can be verified with below command in terminal,
```
$ curl -XGET 'https://elasticsearch:9200/_template/units?pretty'
{ }
```
4. elasticsearch-dump is expected to return the result of elasticsearch query instead of empty error. It is expected to return {} same as elasticsearch response in point 3.

**Comment by ferronrsmith** [comment] 2020-11-17 03:51
duplicate of #742

**Closed by ferronrsmith** 2020-11-17 03:51 UTC
